metadata:
  title: 'Yamanashi Tech Events API'
  description: 'This is an API for Tech events in Yamanashi prefecture.'
  version: '1.4.0'

api_client:
  user_agent: 'YamanashiTechEventAPI/{version} (+https://github.com/yuukis/yamanashi-event-api)'

recent_days: 120

scope:
  prefecture:
    - '山梨県'

  subdomain:
    - 'jagyamanashi' # 日本Androidの会 山梨支部
    - 'coderdojokofu' # 子ども向けプログラミングクラブ コーダー道場甲府
    - 'redmine-plugin-ymanasi' # Redmineプラグインもくもく会 山梨
    - 'shingenpy' # shingen.py
    - 'coderdojo-hokuto' # 子どものためのプログラミングクラブ CoderDojo北杜
    - 'coderdojo-nirasaki' # 子どものためのプログラミングクラブ CoderDojo韮崎
    - 'yamanashi-it' # 山梨IT同好会(仮)
    - 'fujimokumokukai' # 富士もくもく会
    - 'yamanashi-web' # 山梨Web勉強会
    - 'yamanashi-spa' # 山梨SPA
    - 'gdg-yamanashi' # GDG Yamanashi
    - 'kainokuni' # 甲斐国もくもく会
    - 'jaws-ug-yamanashi' # JAWS-UG山梨
    - 'houtoupm' # Houtou.pm
    - 'aibase' # AI BASE
    - 'kofurb' # Kofu.rb
    - 'ai-meetup' # 東京-山梨 AI ミートアップ
    - 'yamanashi-encareer' # やまなしエンxキャリ（Engineer × Career）

  icalendar:
    - key: 'yamanashi-wordpress-meetup'
      name: 'Yamanashi WordPress Meetup'
      image_url: https://secure-content.meetupstatic.com/images/classic-events/488365181/72x72.jpg
      group_url: https://www.meetup.com/ja-JP/yamanashi-wordpress-meetup/
      ical_url: https://www.meetup.com/ja-JP/Yamanashi-WordPress-Meetup/events/ical/
    - key: 'yamanashi-it-meetup-tmp'
      name: '山梨ITコミュニティ合同イベント(仮)'
      group_url: https://connpass.com/event/380532/
      ical_url: https://calendar.google.com/calendar/ical/2b863c0b05baf9bbf615aad330758ab2701cc000aa394af3c33e93dc92aeeaab%40group.calendar.google.com/public/basic.ics
